#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: #@ data.values.xrd.names.plural + "." + data.values.xrd.group
spec:
  group: #@ data.values.xrd.group
  names: #@ data.values.xrd.names
  claimNames: #@ data.values.xrd.claimNames
  connectionSecretKeys:
  - type
  - provider
  - host
  - port
  - database
  - username
  - password
  versions:

  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                  #! providerConfig:
                  #!   type: string
                  #!   default: default
                  version:
                    type: string
                    default: "13"
                    enum: ["11", "12", "13"]
                  adminUsername:
                    type: string
                    default: postgres
                  storageClass:
                    type: string
                    default: default
                  database:
                    type: string
                    default: postgres
                  #! instanceKind:
                  #!   type: string
                  #!   default: "default"
                  #!   enum: ["default", "high-performance"]
                  #! storageSize:
                  #!   type: string
                  #!   default: "small"
                  #!   enum: ["small", "medium", "large"]
                  collation:
                    type: string
                    default: "en_US.utf8"
                  charset:
                    type: string
                    default: "utf8"  
                  #! firewallRule:
                  #!   type: object
                  #!   default: 
                  #!     startIpAddress: "0.0.0.0"
                  #!     endIpAddress: "0.0.0.0"
                  #!   properties:
                  #!     startIpAddress:
                  #!       type: string
                  #!     endIpAddress:
                  #!       type: string
                  #!   required:
                  #!   - startIpAddress
                  #!   - endIpAddress
                required:
                - location
            required:
            - parameters
          status:
            type: object
            properties:
              address:
                type: string
              location:
                type: string
    additionalPrinterColumns:
    - name: address
      type: string
      jsonPath: .status.address
    - name: location
      type: string
      jsonPath: .status.location
    - name: connection-details
      type: string
      jsonPath: .spec.publishConnectionDetailsTo.name