#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: #@ (data.values.xrd.claimNames.kind).lower()
  labels:
    crossplane.io/xrd: #@ data.values.xrd.names.plural + "." + data.values.xrd.group
    provider: #@ data.values.provider.name
    database: #@ data.values.cloudServiceBindingType
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: #@ data.values.storeConfig.name
  compositeTypeRef:
    apiVersion: #@ data.values.xrd.group + "/" + data.values.xrd.version
    kind: #@ data.values.xrd.names.kind
  resources:
  - name: resourcegroup
    base: 
      apiVersion: azure.upbound.io/v1beta1
      kind: ResourceGroup
      spec: {}    
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.location
      toFieldPath: spec.forProvider.location
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.resourceGroup
  - name: flexibleserver
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FlexibleServer
      spec:
        providerConfigRef:
          name: #@ data.values.provider.configRef
        forProvider:
          resourceGroupNameSelector:
            matchControllerRef: true
          administratorLogin: psqladmin
          administratorPasswordSecretRef:
            key: password
            name: ""
            namespace: #@ data.values.crossplane.namespace
          location: West Europe
          skuName: GP_Standard_D4s_v3
          storageMb: 32768
          version: "12" #! 11,12 and 13 are supported
    connectionDetails:
    - name: type
      value: postgresql
    - name: provider
      value: azure
    - name: database
      value: postgres
    - name: username
      fromFieldPath: spec.forProvider.administratorLogin
    - name: password
      fromConnectionSecretKey: "attribute.administrator_password"
    - name: host
      fromFieldPath: status.atProvider.fqdn
    - name: port
      type: FromValue
      value: "5432"
    patches:
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - string:
          fmt: '%s-postgresql'
          type: Format
        type: string
      type: FromCompositeFieldPath
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.administratorPasswordSecretRef.name
  - name: flexibleserverconfig
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FlexibleServerConfiguration
      spec:
        providerConfigRef:
          name: #@ data.values.provider.configRef
        forProvider:
          serverIdSelector:
            matchControllerRef: true
          name: backslash_quote
          value: on  
  - name: flexibleserverdatabase
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FlexibleServerDatabase
      spec:
        providerConfigRef:
          name: #@ data.values.provider.configRef
        forProvider:
          serverIdSelector:
            matchControllerRef: true
          charset: ""
          collation: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.charset
      toFieldPath: spec.forProvider.charset
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.collation
      toFieldPath: spec.forProvider.collation
  - name: firewallrule
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: FlexibleServerFirewallRule
      spec:
        providerConfigRef:
          name: #@ data.values.provider.configRef
        forProvider:
          serverIdSelector:
            matchControllerRef: true
          startIpAddress: ""
          endIpAddress: ""
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.firewallRule.startIpAddress
      toFieldPath: spec.forProvider.startIpAddress
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.firewallRule.endIpAddress
      toFieldPath: spec.forProvider.endIpAddress
  - name: password
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: secretgen.k14s.io/v1alpha1
            kind: Password
            metadata:
              name: ""
              namespace: #@ data.values.crossplane.namespace
            spec:
              length: 64
              secretTemplate:
                type: Opaque
                stringData:
                  password: $(value)
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name


#! location: ""
#! server:
#!   version: "13"
#!   instanceKind: [default, high-performance] 
  #!   instance_type: "Standard_D2s_v3"
  #!   instance_tier: "GeneralPurpose"
#!   storageSize: [small, medium, large] (64, 256, 1024)
  #!   instance_storage_size_gb: 128
#! firewall_rules:
#!     startIpAddress: ""
#!     endIpAddress: ""