#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  name: #@ data.values.metadata.name
spec:
  packageRef:
    refName: #@ data.values.metadata.name
    versionSelection:
      constraints: #@ data.values.version
  serviceAccountName: #@ "-".join(data.values.metadata.name.split(".")[0:2])
