apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: psql.google.references.services.apps.tanzu.vmware.com.0.0.1-alpha
spec:
  refName: psql.google.references.services.apps.tanzu.vmware.com
  version: 0.0.1-alpha
  releasedAt: "2022-07-14T14:47:00+02:00"
  releaseNotes: https://docs.vmware.com/en/Services-Toolkit-for-VMware-Tanzu/0.7/services-toolkit-0-7/GUID-overview.html
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        name:
          title: Service Instance Name
          type: string
          description: The name of the Cloud SQL instance and related objects
          default: ''
        namespace:
          title: Service Instance Namespace
          type: string
          nullable: true
          description: The namespace the service instance objects should be deployed into
          default: null
        version:
          type: string
          description: 'The database version of the Cloud SQL instance

            see: https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance#:~:text=Fields-,databaseVersion,-Optional'
          default: POSTGRES_14
        region:
          title: Database Region
          type: string
          description: 'The region this Cloud SQL instance should be deployed into

            see: https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance#:~:text=with%2Dobjects/namespaces/-,region,-Optional'
          default: europe-west6
        tier:
          title: Database Machine Type
          type: string
          description: 'The machine type for the Cloud SQL instance

            see: https://cloud.google.com/config-connector/docs/reference/resource-docs/sql/sqlinstance#:~:text=from%20your%20configuration.-,settings.tier,-Required'
          default: db-g1-small
        labels:
          title: Labels
          nullable: true
          description: A set of labels which will be applied to all resources related to
            this instance
          x-example-description: Set custom labels on all objects
          example:
            mycorp.io/service-type: gcp-sql
            mycorp.io/owner: me@mycorp.io
          default:
            app.kubernetes.io/component: cloudsql-postgres
        serviceInstanceLabels:
          title: Service Instance Labels
          nullable: true
          description: A set of labels which will be applied to the claimable secret
          default:
            services.apps.tanzu.vmware.com/class: cloudsql-postgres
        allowedNetworks:
          title: Allowed Networks
          type: array
          nullable: true
          description: A list of CIDR ranges allowed to talk to this Cloud SQL instance
          x-example-description: Allow one (named) network & one host
          example:
            - name: my-onprem-net
              value: 11.22.33.44/24
            - value: 8.8.8.8/32
          items:
            type: object
            additionalProperties: false
            properties:
              name:
                type: string
                nullable: true
                description: the name for the authorized/allowed network (optional)
                default: null
              value:
                type: string
                description: the IPv4 CIDR of the authorized/allowed network
                default: ''
          default: null
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/vmware-tanzu/tanzu-application-platform-reference-service-packages/psql.google.references.services.apps.tanzu.vmware.com@sha256:9fc1a2767adac504e06d6eb8c9b2cbecc887ad605e3652401f26dc101abd1c6d
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - "-"
          - ".imgpkg/images.yml"
      deploy:
      - kapp: {}
