---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rds-install
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rds-install
rules:
- apiGroups: ["*"] # TODO: use more fine-grained RBAC permissions
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rds-install
subjects:
- kind: ServiceAccount
  name: rds-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rds-install
