---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudsql-install
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudsql-install
rules:
- apiGroups: ["sql.cnrm.cloud.google.com"]
  resources: ["sqlinstances","sqldatabases","sqlusers"]
  verbs:     ["*"]
- apiGroups: ["secretgen.carvel.dev", "secretgen.k14s.io"]
  resources: ["secrettemplates","passwords"]
  verbs:     ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts","configmaps"]
  verbs:     ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs:     ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudsql-install
subjects:
- kind: ServiceAccount
  name: cloudsql-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudsql-install
