---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudsql-install
  namespace: default
---
#! : kapp inspect -a cloudsql-1-ctrl -n service-instances -t
#!
#! Namespace          Name                              Kind            Owner    Rs  Ri  Age
#! service-instances  cloudsql-1                        SQLInstance     kapp     ok  -   16h
#! service-instances  cloudsql-1                        SQLUser         kapp     ok  -   16h
#! service-instances  cloudsql-1-obj-reader             ServiceAccount  kapp     ok  -   16h
#! service-instances  cloudsql-1-cloudsql-1-cloudsql-1  SecretTemplate  kapp     ok  -   16h
#! service-instances  cloudsql-1-cloudsql-1-creds       Password        kapp     ok  -   16h
#! service-instances   L cloudsql-1-cloudsql-1-creds    Secret          cluster  ok  -   16h
#! service-instances  cloudsql-1                        SQLDatabase     kapp     ok  -   16h
#! service-instances  cloudsql-1-obj-reader             Role            kapp     ok  -   16h
#! service-instances  cloudsql-1-admin-creds            Password        kapp     ok  -   16h
#! service-instances   L cloudsql-1-admin-creds         Secret          cluster  ok  -   16h
#! service-instances  cloudsql-1-obj-reader             RoleBinding     kapp     ok  -   16h

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudsql-install
  namespace: default
rules:
- apiGroups: ["sql.cnrm.cloud.google.com"]
  resources: ["sqlinstances","sqldatabases","sqlusers"]
  verbs:     ["*"]
- apiGroups: ["secretgen.carvel.dev", "secretgen.k14s.io"]
  resources: ["secrettemplates","passwords"]
  verbs:     ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts","configmaps"]
  verbs:     ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs:     ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudsql-install
  namespace: default
subjects:
- kind: ServiceAccount
  name: cloudsql-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudsql-install
