name: Reusable workflow for testing Carvel packages

on:

  workflow_call:

    inputs:
      repo_version:
        type: string
        required: true
      package_version:
        type: string
        required: true
      package_name:
        type: string
        required: true
      package_provider:
        type: string
        required: true
      kubernetes-version:
        type: string
        default: v1.24.6
      kind-version:
        type: string
        default: v0.16.0
      kapp-controller-version:
        type: string
        default: v0.43.2

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      KAPP_GLOBAL_NAMESPACE: kapp-controller-packaging-global

    steps:

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          verbosity: 5
          version: ${{ inputs.kind-version }}
          kubectl_version: ${{ inputs.kubernetes-version }}
          node_image: kindest/node:${{ inputs.kubernetes-version }}

      - name: Verify Cluster
        run: |
          kubectl version
          which kubectl
          kubectl cluster-info
          kubectl get storageclass standard

      - name: Install kapp-controller
        run: |
          KAPP_MANIFEST="https://github.com/vmware-tanzu/carvel-kapp-controller/releases/download/${{ inputs.kapp-controller-version }}/release.yml"
          if [[ "${{ inputs.kapp-controller-version }}" == "latest" ]]; then
            KAPP_MANIFEST="https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml"
          fi
          kubectl apply -f https://github.com/vmware-tanzu/carvel-secretgen-controller/releases/latest/download/release.yml

          kubectl apply -f $KAPP_MANIFEST
          kubectl wait --for=condition=Available=True apiservices.apiregistration.k8s.io v1alpha1.data.packaging.carvel.dev

      - name: Install Carvel repository
        run: |
          kubectl apply -n $KAPP_GLOBAL_NAMESPACE -f https://github.com/${{ github.repository }}/releases/download/${{ inputs.repo_version }}/package-repository.yml

      - name: List available packages
        run: |
          kubectl get packages.data.packaging.carvel.dev
