name: Reusable workflow for publishing Crossplane packages

on:

  workflow_call:

    inputs:
      package_version:
        type: string
        required: true
      package_name:
        type: string
        required: true
      package_provider:
        type: string
        required: true
      run-test:
        type: boolean
        default: false
      kubernetes-version:
        type: string
        default: v1.24.6
      kind-version:
        type: string
        default: v0.16.0

    outputs:
      package_repository:
        value: ${{ jobs.publish.outputs.package_repository }}
      package_registry:
        value: ${{ jobs.publish.outputs.package_registry }}

jobs:

  publish:
    runs-on: ubuntu-latest

    outputs:
      package_repository: ${{ env.PACKAGE_REPOSITORY }}
      package_registry: ${{ env.PACKAGE_REGISTRY }}

    env:
      PACKAGE_VERSION: ${{ inputs.package_version }}
      PACKAGE_REGISTRY: ghcr.io
      PACKAGE_REPOSITORY: ${{ github.repository }}/${{ inputs.package_provider }}/crossplane/${{ inputs.package_name }}
      PACKAGE_PROVIDER: ${{ inputs.package_provider }}
      PACKAGE_NAME: ${{ inputs.package_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.package_version }}

      - name: Install UXP
        run: |
          curl -sL "https://cli.upbound.io" | sh
          sudo mv up /usr/local/bin/
          up --version

      - name: Install Carvel tools
        uses: vmware-tanzu/carvel-setup-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          only: ytt

      - name: Log in to ${{ env.PACKAGE_REGISTRY }}
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9  # v1.10.0
        with:
          registry: ${{ env.PACKAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Dump info
        run: |
          env | sort

      - name: Crossplane Package Publish
        run: |
          make crossplane-push

  test:
    if: inputs.run-test
    uses: ./.github/workflows/reusable-crossplane-test.yml
    needs:
      - publish
    with:
      package_version: ${{ inputs.package_version }}
      package_name: ${{ inputs.package_name }}
      package_provider: ${{ inputs.package_provider }}
      package_registry: ${{ needs.publish.outputs.package_registry }}
      package_repository: ${{ needs.publish.outputs.package_repository }}
